#server:
#  port: 8088
#
#spring:
#  datasource:                                           # 数据源的相关配置
#    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
#    password: root
#  redis:
#    database: 1
#    host: 39.100.152.63
#    port: 6379
#    password: Leadingsoft2019
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl